modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="sologates"
version="${file.jarVersion}"
displayName="Solo Gates"
authors="matis"
description='''Solo Leveling inspired dungeon gates with ranks, random monsters, failure invasions and configurable rewards.'''

[[dependencies.sologates]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.sologates]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
