view-distance=7
simulation-distance=5
max-players=50
online-mode=true
enforce-whitelist=false
spawn-protection=16
allow-flight=true
difficulty=hard
gamemode=survival
pvp=true
motd=Dungeon Arise
sync-chunk-writes=true
network-compression-threshold=256
entity-broadcast-range-percentage=75
